var DEBUG_ENEMY_MAN = 1;

// 設定
var cvs;
var ctx;

var FIELD_X = 6;
var FIELD_Y = 8;
var FIELD_SIZE = 50;
var FIELD_PADDING_X = 0;
var FIELD_PADDING_Y = 0;

var FIELD_NONE_BY_SHIRE = 4; // 司令塔により削除されているマス

var MAN_SIZE_W = 40;
var MAN_SIZE_H = 45;

// 駒の画像を保持する
var manImage = [];
var skinName = "skin2";

// 駒の種類の配列
var manType = [];

// 自駒の配列
var myMen = [];
// 敵駒の配列
var enemyMen = [];

// 将棋盤の状況 / 棋譜
var field = [];
var hands = [];

// 現在の状態を保存しておく
var stage = 0;
var target = null;

// 駒のenum
var SHOGI = {
  TAISHO: 0,
  CHUSHO: 1,
  SHOSHO: 2,
  TAISA : 3,
  CHUSA : 4,
  SHOSA : 5,
  TAII  : 6,
  CHUI  : 7,
  SHOI  : 8,
  HIKOKI: 9,
  TANK  :10,
  KIHEI :11,
  KOHEI :12,
  SUPAI :13,
  JIRAI :14,
  GUNKI :15,
};

// 表示用の日本語
var SHOGI_JA = {}
SHOGI_JA[SHOGI.TAISHO] = '大将';
SHOGI_JA[SHOGI.CHUSHO] = '中将';
SHOGI_JA[SHOGI.SHOSHO] = '小将';
SHOGI_JA[SHOGI.TAISA]  = '大佐';
SHOGI_JA[SHOGI.CHUSA]  = '中佐';
SHOGI_JA[SHOGI.SHOSA]  = '小佐';
SHOGI_JA[SHOGI.TAII]   = '大尉';
SHOGI_JA[SHOGI.CHUI]   = '中尉';
SHOGI_JA[SHOGI.SHOI]   = '小尉';
SHOGI_JA[SHOGI.HIKOKI] = '飛行機';
SHOGI_JA[SHOGI.TANK]   = 'タンク';
SHOGI_JA[SHOGI.KIHEI]  = '騎兵';
SHOGI_JA[SHOGI.KOHEI]  = '工兵';
SHOGI_JA[SHOGI.SUPAI]  = 'スパイ';
SHOGI_JA[SHOGI.JIRAI]  = '地雷';
SHOGI_JA[SHOGI.GUNKI]  = '軍旗';

// 画像用の配列
var SHOGI_EN = {}
SHOGI_EN[SHOGI.TAISHO] = 'taisho';
SHOGI_EN[SHOGI.CHUSHO] = 'chusho';
SHOGI_EN[SHOGI.SHOSHO] = 'shosho';
SHOGI_EN[SHOGI.TAISA]  = 'taisa';
SHOGI_EN[SHOGI.CHUSA]  = 'chusa';
SHOGI_EN[SHOGI.SHOSA]  = 'shosa';
SHOGI_EN[SHOGI.TAII]   = 'taii';
SHOGI_EN[SHOGI.CHUI]   = 'chui';
SHOGI_EN[SHOGI.SHOI]   = 'shoi';
SHOGI_EN[SHOGI.HIKOKI] = 'hikoki';
SHOGI_EN[SHOGI.TANK]   = 'tank';
SHOGI_EN[SHOGI.KIHEI]  = 'kihei';
SHOGI_EN[SHOGI.KOHEI]  = 'kohei';
SHOGI_EN[SHOGI.SUPAI]  = 'supai';
SHOGI_EN[SHOGI.JIRAI]  = 'jirai';
SHOGI_EN[SHOGI.GUNKI]  = 'gunki';

// 勝敗表
var RESULT = {
  WIN: 1,
  DRW: 2,
  LOS: 3,
};

var standings = [];
standings[SHOGI.TAISHO] = [RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.LOS,RESULT.DRW,RESULT.WIN];
standings[SHOGI.CHUSHO] = [RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.SHOSHO] = [RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.TAISA]  = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.CHUSA]  = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.SHOSA]  = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.TAII]   = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.CHUI]   = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.SHOI]   = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.HIKOKI] = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN];
standings[SHOGI.TANK]   = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.WIN,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.LOS,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.KIHEI]  = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.DRW,RESULT.WIN];
standings[SHOGI.KOHEI]  = [RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.WIN,RESULT.LOS,RESULT.DRW,RESULT.WIN,RESULT.WIN,RESULT.WIN];
standings[SHOGI.SUPAI]  = [RESULT.WIN,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.LOS,RESULT.DRW,RESULT.DRW,RESULT.WIN];
standings[SHOGI.JIRAI]  = [RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.LOS,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.DRW,RESULT.WIN];